language: node_js
node_js:
- '6'
before_install: |
    set -ev
    set -o pipefail
    npm install -g npm
    npm install -g @alrra/travis-scripts
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        branch: master 
cache:
  directories:
    - node_modules
