language: node_js
node_js:
- '6'
before_install: |
    set -ev
    set -o pipefail
    npm install -g npm
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
cache:
  directories:
  - $HOME/.npm
