language: node_js
node_js:
- '4'
- '6'
dist: trusty
before_install: |
    set -ev
    set -o pipefail
    npm install -g npm
deploy:
    provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
        all_branches: true
cache:
  directories:
  - $HOME/.npm
